[Enhancement] set initial layer config when set layer type
keplergl/kepler.gl pull request #1898
Opened 2022-08-03 15:56 UTC by jwasilgeo

Signed-off-by: Shan He <heshan0131@gmail.com>

[Bug] fix setting layer type override layer name (UN-1863)

Signed-off-by: Shan He <heshan0131@gmail.com>
Signed-off-by: Jacob Wasilkowski <jwasilkowski@foursquare.com>

2022-08-03 21:26 UTC, heshan0131 approved these changes

2022-08-03 21:27 UTC, heshan0131 commented
please make sure to remove (UN-1863) from the final squashed commit message

2022-08-03 21:27 UTC, igorDykhta approved these changes

2022-08-03 21:29 UTC, igorDykhta requested changes

2022-08-03 21:29 UTC, igorDykhta commented on src/layers/src/h3-hexagon-layer/h3-hexagon-layer.ts
> +    if (!dataset.allData?.length) {
dataset.dataContainer.runRows()

2022-08-03 21:29 UTC, igorDykhta commented on src/layers/src/point-layer/point-layer.ts
> +    if (!dataset.allData?.length) {
dataset.dataContainer.runRows()

2022-08-03 23:48 UTC, heshan0131 commented
Same here...remove UN-1863 from squashed message

2022-08-04 01:34 UTC, jwasilgeo commented
Good catch, I cleaned that up @heshan0131, thanks.

2022-08-04 01:44 UTC, igorDykhta approved these changes

2022-08-04 01:44 UTC, jwasilgeo commented on src/layers/src/point-layer/point-layer.ts
> +    if (!dataset.allData?.length) {
ce42561

2022-08-04 01:45 UTC, jwasilgeo commented on src/layers/src/h3-hexagon-layer/h3-hexagon-layer.ts
> +    if (!dataset.allData?.length) {
ce42561

2022-08-04 01:58 UTC, merged